# This is a generated file. Not intended for manual editing.
services:
  evently.api:
    build:
      context: "X:\\Repos\\Evently"
      dockerfile: "Evently.Api/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net9.0/Evently.Api.dll"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "evently.api:dev"
    ports: []
    volumes:
    - "X:\\Repos\\Evently\\Evently.Api:/app:rw"
    - "X:\\Repos\\Evently:/src:rw"
    - "C:\\Users\\realb\\.nuget\\packages:/home/app/.nuget/packages"
    working_dir: "/app"
